name: 'action-migrations'
description: 'Actions related to django migrations in sentry'
author: 'sentry.io'
inputs:
  migration:
    description: 'file name (or number) for the migration'
  githubToken:
    description: 'GitHub Token (available as `secrets.GITHUB_TOKEN`)'
runs:
  using: 'node12'
  main: 'dist/index.js'
